# Generated by Django 3.2.8 on 2021-10-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_pop'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='coin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
